DROP TABLE IF EXISTS expediente_archivo;

CREATE TABLE expediente_archivo (
    ID_EXPEDIENTE INT NOT NULL PRIMARY KEY,
    CODIGO_UNICO VARCHAR(64) NOT NULL,
    ALEAS_EXPEDIENTE VARCHAR(128) NULL,
    NOMBRE_PERSONA_EXPEDIENTE VARCHAR(128) NULL,
    IDENTIFICACION_PERSONA_EXPEDIENTE VARCHAR(64) NULL,
    NOMBRE_RESPONSABLE_EXPEDIENTE VARCHAR(128) NULL,
    IDENFICACION_RESPONSABLE_EXPEDIENTE VARCHAR(64) NULL
);
